# Generated by Django 4.0 on 2021-12-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fnltst_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priority',
            new_name='rate',
        ),
    ]
