# Generated by Django 4.0 on 2021-12-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fnltst_App', '0002_rename_priority_task_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images'),
            preserve_default=False,
        ),
    ]
